#!/usr/bin/env bash
# make_xml.sh — reproduce XML/Truku/Hsu_Lowking_Truku_WordFormation_2008.xml
# from the committed inputs under CodeAndDocs/data/.
#
# The build is runnable WITHOUT the source PDF extraction steps: steps 1-13 of
# the Phase 1 pipeline (PDF decrypt/extract/parse/normalize/filter/dedupe) have
# their outputs committed under data/processed/, and build_formosanbank_xml
# reads only those intermediates plus data/manual/manual_sentences.xml (the
# hand-curated additions/overrides file, merged by S id — see README "Manual
# edits"). Rerun the earlier steps only if the parse itself must change.
#
# This script is the ONLY entry point: it calls scripts/pipeline.py --step <name>
# directly (there are no per-step wrapper scripts) and then the FormosanBank QC
# tools from the repo root.
#
# Run from anywhere; paths are resolved relative to this script.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"     # .../CodeAndDocs
CORPUS_DIR="$(dirname "$HERE")"                          # .../Nowbucyang-Truku-Thesis
BANK="$(cd "$CORPUS_DIR/../.." && pwd)"                  # FormosanBank repo root
PY="${PY:-$BANK/.venv/bin/python}"

BUILD_XML_DIR="$HERE/Final_XML"                          # Phase 1 build target (temporary)

echo "== Phase 1: build Final_XML from committed data/ inputs =="
"$PY" "$HERE/scripts/pipeline.py" --step build_formosanbank_xml --config "$HERE/scripts/config.yaml"
"$PY" "$HERE/scripts/pipeline.py" --step validate_formosanbank_xml --config "$HERE/scripts/config.yaml"

echo "== Phase 2: FormosanBank QC pipeline over the built XML =="
cd "$BANK"
# 0. recorded hand edits FIRST (POL-030). CodeAndDocs/manual_edits.xml holds the
#    nine W/M-less sentences whose original tier the maintainer ruled must carry
#    no segmentation markers (2026-08-12 ruling): they were never fully glossed,
#    so they get no W/M tier and no `-`/`=` notation. The records hold only the
#    original FORM + TRANSL — standard FORM and PHON are regenerated by the
#    steps below (POL-002/003).
"$PY" QC/cleaning/apply_manual_edits.py --corpora_path "$BUILD_XML_DIR" \
    --manual_file "$HERE/manual_edits.xml"
# 1. typography/character canonicalization (POL-010/011/012/013). The Truku
#    attestation dictionary is intentionally absent, so quote-glottal
#    correction stays disarmed for this corpus.
"$PY" QC/cleaning/clean_xml.py --corpora_path "$BUILD_XML_DIR"
# 2. standard tier: Ortho94 -> Ortho113 via the Seediq table's Truku column
#    (selected by TEXT@dialect="Truku"). The Truku column currently carries no
#    letter conversions, so this is copy + accent strip + null-unit removal +
#    C012 S-level de-segmentation — standardize owns all standard-tier
#    cleaning per POL-002.
"$PY" QC/utilities/standardize.py --corpora_path "$BUILD_XML_DIR" \
    --tsv_path Orthographies/ConversionTables/Seediq_94_113.tsv
# 3. residual-duplicate merge (POL-022/POL-025). Phase 1 already declares a
#    dedup step (dedupe_examples + dedupe_against_formosanbank), but its key is
#    the exact (Truku form, Chinese translation) PAIR, so sentences repeated
#    across thesis examples with a differently-worded free translation survive
#    it. `--tier original` is the discriminator the maintainer's 2026-08-12
#    ruling asks for: groups whose ORIGINAL forms are identical are the same
#    source sentence twice and get the POL-025 merge (survivor keeps the extra
#    TRANSLs as ver="alt", duplicate deleted); groups that agree only after
#    de-segmentation (e.g. `N-nima` vs `Nnima`) differ in the source's own
#    morpheme notation and are RETAINED DELIBERATELY as distinct attestations
#    (POL-022 distinct-provenance nuance) — see README "Known QC state".
#    Runs before add_phonology so PHON is generated for the final S set and the
#    final file is prettified by add_phonology.
"$PY" QC/cleaning/remove_duplicate_sentences.py by_path --path "$BUILD_XML_DIR" \
    --tier original --scope file --apply
# 4. PHON tiers: original PHON from Ortho94, standard PHON from Ortho113
#    (both via the Seediq profiles' Truku dialect column).
"$PY" QC/utilities/add_phonology.py --corpora_path "$BUILD_XML_DIR" --orthography Ortho94

echo "== Publish into XML/ and clean up =="
mkdir -p "$CORPUS_DIR/XML/Truku"
mv "$BUILD_XML_DIR/Truku/Hsu_Lowking_Truku_WordFormation_2008.xml" \
   "$CORPUS_DIR/XML/Truku/Hsu_Lowking_Truku_WordFormation_2008.xml"
# Removing the build dir also drops the per-run cleaner_warnings.csv /
# standardize_warnings.csv reports (POL-033: never committed). Any
# quote_corrections.csv here would be unexplained — Truku's attestation
# dictionary is deliberately absent, so quote correction cannot arm.
if [ -f "$BUILD_XML_DIR/quote_corrections.csv" ]; then
    echo "ERROR: unexpected quote_corrections.csv (Truku quote correction is disarmed)" >&2
    exit 1
fi
rm -rf "$BUILD_XML_DIR"

echo "Done: $CORPUS_DIR/XML/Truku/Hsu_Lowking_Truku_WordFormation_2008.xml"
