#!/usr/bin/env python3
"""Resolve the source parenthetical notation left after pipeline step 20.

The earlier optional-material steps handle whole optional words and clean
slash alternatives.  The NTU source also contains optional phonemes,
affixes, and phrases whose parentheses can cross morpheme or word element
boundaries.  POL-026 requires explicit optional material to become complete,
aligned sentence variants, not parenthesis-bearing W/M forms.

This script has three deliberately separate paths:

* balanced parentheses present in the sentence FORM are materialized as all
  source-explicit with/without combinations;
* balanced parentheses present only in W/M analysis are stripped while the
  sentence's attested surface is retained;
* a small source-located exception table repairs parser column shifts,
  annotation leakage, already-expanded slash choices, and three ambiguous
  cross-word spans for which an omitted analysis is not recoverable.

The original sentence becomes the all-omitted reading.  Additional readings
receive deterministic ``-optN`` suffixes.  AUDIO stays on the original only,
matching the convention used by ``split_optional_parentheticals.py``.  PHON
is removed only from changed sentences and is regenerated by the canonical
``add_phonology.py`` step immediately after this script in ``make.sh``.

Every exception is keyed by a stable source-derived sentence id.  The raw
JSON remains unchanged and therefore remains the primary audit witness.
The operation is deterministic and idempotent.
"""

from __future__ import annotations

import argparse
import collections
import copy
import os
import re
from pathlib import Path

import lxml.etree as etree


_XLANG = "{http://www.w3.org/XML/1998/namespace}lang"
_PUNCT_ONLY = re.compile(r"^[\s\-=/.,!?;:，。！？；：]*$")


# Slash expansion has already selected these source alternatives.  The
# opening/closing parentheses belong to the original slash expression, not
# to a new optional span.
STRIP_ONLY_SENTENCES = {
    "3_S_109_v1",
    "3_S_109_v2",
    "3_S_122_v1",
    "3_S_122_v2",
    "3_S_194_v1",
    "3_S_194_v2",
    "3_S_207_v1",
    "3_S_207_v2",
}


# These source spans cross a word boundary inside a morpheme-like string.
# Both endpoints are recoverable, but deleting the parenthesized middle would
# require inventing a new word segmentation.  Keep the full source-listed
# form, strip the notation, and record why no guessed omitted variant exists.
CROSS_WORD_KEEP_SENTENCES = {
    "bnNr-frog_Laniahu_S_21",
    "bnNr-frog_Laniahu_S_26",
    "bnNr-pear_Laniahu_S_70",
}


from source_repair_registry import (
    load_indexed_optional_words,
    load_special_form_cases,
)


INDEXED_OPTIONAL_WORDS = load_indexed_optional_words()
_SPECIAL_FORM_CASES = load_special_form_cases()
RUKAI_OPTIONAL_PREFIX = _SPECIAL_FORM_CASES["rukaiOptionalPrefix"]
RUKAI_UNALIGNED_SLASH_FORM = _SPECIAL_FORM_CASES["rukaiUnalignedSlash"]
RUKAI_POSITIONAL_ALTERNATIVE = (
    _SPECIAL_FORM_CASES["rukaiPositionalAlternative"]
)


def _tier(parent, tag, kind):
    return next(
        (child for child in parent.findall(tag)
         if child.get("kindOf") == kind),
        None,
    )


def _translation(parent, lang):
    return next(
        (child for child in parent.findall("TRANSL")
         if child.get(_XLANG) == lang and child.get("ver") is None),
        None,
    )


def _append_note(form, note):
    existing = (form.get("notes") or "").strip()
    if note in existing:
        return
    form.set("notes", f"{existing}; {note}" if existing else note)


def _remove_phon(sentence):
    for phon in list(sentence.xpath(".//PHON")):
        phon.getparent().remove(phon)


def _strip_parens(text):
    return (text or "").replace("(", "").replace(")", "")


def _strip_sentence_notation(sentence, note):
    changed = False
    for element in sentence.xpath(".//FORM | .//TRANSL"):
        if element.text and ("(" in element.text or ")" in element.text):
            element.text = _strip_parens(element.text)
            changed = True
        notes = element.get("notes")
        if notes and ("(" in notes or ")" in notes):
            # Notes are evidence, not validator input.  Do not rewrite them.
            continue
    if changed:
        original = _tier(sentence, "FORM", "original")
        if original is not None:
            _append_note(original, note)
        _remove_phon(sentence)
    return changed


def _set_form(parent, value):
    for kind in ("original", "standard"):
        form = _tier(parent, "FORM", kind)
        if form is not None:
            form.text = value


def _set_primary_translation(parent, lang, value):
    element = _translation(parent, lang)
    if element is None:
        element = etree.Element("TRANSL")
        element.set(_XLANG, lang)
        first_word = parent.find("W")
        if first_word is None:
            parent.append(element)
        else:
            parent.insert(parent.index(first_word), element)
    element.text = value


def _add_alt_translation(parent, lang, value):
    for element in parent.findall("TRANSL"):
        if element.get(_XLANG) == lang and (element.text or "") == value:
            if element is not _translation(parent, lang):
                element.set("ver", "alt")
            return
    element = etree.Element("TRANSL")
    element.set(_XLANG, lang)
    element.set("ver", "alt")
    element.text = value
    words = parent.findall("W")
    insert_at = parent.index(words[0]) if words else len(parent)
    parent.insert(insert_at, element)


def _make_word(sid, index, form, eng, zho, *, form_note=None):
    word = etree.Element("W", id=f"{sid}_W{index}")
    original = etree.SubElement(word, "FORM", kindOf="original")
    original.text = form
    if form_note:
        original.set("notes", form_note)
    standard = etree.SubElement(word, "FORM", kindOf="standard")
    standard.text = form
    zho_t = etree.SubElement(word, "TRANSL")
    zho_t.set(_XLANG, "zho")
    zho_t.text = zho
    eng_t = etree.SubElement(word, "TRANSL")
    eng_t.set(_XLANG, "eng")
    eng_t.text = eng
    morph = etree.SubElement(word, "M", id=f"{sid}_W{index}M1")
    m_original = etree.SubElement(morph, "FORM", kindOf="original")
    m_original.text = form
    m_standard = etree.SubElement(morph, "FORM", kindOf="standard")
    m_standard.text = form
    m_eng = etree.SubElement(morph, "TRANSL")
    m_eng.set(_XLANG, "eng")
    m_eng.text = eng
    m_zho = etree.SubElement(morph, "TRANSL")
    m_zho.set(_XLANG, "zho")
    m_zho.text = zho
    return word


def _fix_saisiyat_column_shift(sentence):
    sid = sentence.get("id")
    if sid != "SaiNr-election_lahi_ a taro_ babay_S_48":
        return False
    words = sentence.findall("W")
    if len(words) < 8 or "money(ita'" not in (
            _tier(words[7], "FORM", "original").text or ""):
        return False

    source_form = "So min'itol ma' noka a moto nasia money(ita'."
    corrected = "So min'itol ma' noka a moto nasia hayza' ka biyae'."
    _set_form(sentence, corrected)
    original = _tier(sentence, "FORM", "original")
    _append_note(
        original,
        "source JSON row 115 uses ori tokens hayza' ka biyae'; the raw "
        "misaligned gloss cell money_(ita' | AF.diligent | 主焦.勤奮 is "
        "preserved here as an audit note; prior generated FORM was "
        f"{source_form}",
    )

    template = words[7]
    position = sentence.index(template)
    tail = template.tail
    sentence.remove(template)
    entries = [
        ("hayza'", "EXIST", "存在", None),
        ("ka", "NOM", "主格", None),
        (
            "biyae'",
            "money",
            "錢",
            "raw source gloss cell: money_(ita' | AF.diligent | 主焦.勤奮",
        ),
    ]
    for offset, (form, eng, zho, note) in enumerate(entries):
        word = _make_word(sid, 7 + offset, form, eng, zho, form_note=note)
        word.tail = tail
        sentence.insert(position + offset, word)
    _remove_phon(sentence)
    return True


def _fix_voiceover_label(sentence):
    if sentence.get("id") != "KavNr-frog_abas_S_80":
        return False
    original = _tier(sentence, "FORM", "original")
    if original is None or "VOICEOVER" not in (original.text or ""):
        return False
    _set_form(sentence, "maiti.")
    _append_note(original, "source transcription label removed from FORM: VOICEOVER")
    word = sentence.find("W")
    _set_form(word, "mai=ti")
    morphs = word.findall("M")
    if len(morphs) != 2:
        raise AssertionError("KavNr-frog_abas_S_80 no longer has two morphemes")
    _set_form(morphs[0], "mai")
    _set_form(morphs[1], "=ti")
    _remove_phon(sentence)
    return True


def _fix_rarely_used_annotation(sentence):
    if sentence.get("id") != "3_S_458":
        return False
    original = _tier(sentence, "FORM", "original")
    if original is None or "(少用)" not in (original.text or ""):
        return False
    for element in sentence.xpath(".//FORM"):
        if element.text:
            element.text = element.text.replace("?(少用).", "?")
            element.text = element.text.replace("?(少用)", "?")
    _append_note(original, "source annotation 少用: rarely used")
    _remove_phon(sentence)
    return True


def _replace_morphemes(word, forms_and_glosses):
    existing = word.findall("M")
    insert_at = word.index(existing[0]) if existing else len(word)
    tail = existing[-1].tail if existing else None
    for morph in existing:
        word.remove(morph)
    for index, (form, eng, zho) in enumerate(forms_and_glosses, start=1):
        morph = etree.Element("M", id=f"{word.get('id')}M{index}")
        etree.SubElement(morph, "FORM", kindOf="original").text = form
        etree.SubElement(morph, "FORM", kindOf="standard").text = form
        eng_t = etree.SubElement(morph, "TRANSL")
        eng_t.set(_XLANG, "eng")
        eng_t.text = eng
        zho_t = etree.SubElement(morph, "TRANSL")
        zho_t.set(_XLANG, "zho")
        zho_t.text = zho
        morph.tail = tail
        word.insert(insert_at + index - 1, morph)


def _fix_rukai_surface_selected_alternative(sentence):
    if sentence.get("id") != "20200531-FW-Lixing_S_19":
        return False
    words = sentence.findall("W")
    if len(words) < 5:
        return False
    word = words[4]
    original = _tier(word, "FORM", "original")
    if original is None or "/" not in (original.text or ""):
        return False

    _set_form(word, "ngu-drusa")
    _append_note(
        original,
        "source S surface ngudusa selects the ngu reading from "
        "ngu-/mu-(a-)drusa; unselected mu-(a-) analysis retained in this note",
    )
    for lang, value in (("eng", "NGU-two"), ("zho", "NGU-二")):
        element = _translation(word, lang)
        if element is not None:
            element.text = value
    _replace_morphemes(word, [("ngu", "NGU", "NGU"), ("drusa", "two", "二")])
    _set_primary_translation(
        sentence, "eng", "All the boys ate two fish each."
    )
    _set_primary_translation(sentence, "zho", "所有男生各吃兩條魚。")
    _add_alt_translation(
        sentence, "eng", "All the boys ate the fish two by two."
    )
    _add_alt_translation(sentence, "zho", "所有男生兩個兩個地吃魚。")
    _remove_phon(sentence)
    return True


def _fix_bunun_quotative_leak(sentence):
    if sentence.get("id") != "bnNr-pear_Laniahu_S_54":
        return False
    original = _tier(sentence, "FORM", "original")
    if original is None or "sin(tupa" not in (original.text or ""):
        return False
    for element in sentence.xpath(".//FORM"):
        if element.text:
            element.text = element.text.replace("sin(tupa", "sintupa")
            element.text = element.text.replace("s<in>(tupa", "s<in>tupa")
            element.text = element.text.replace("s-(tupa", "s-tupa")
    _append_note(
        original,
        "source rows 108-109 split the quotative as s<in>(tupa ... tu); "
        "the parentheses are source annotation leakage, not optional FORM",
    )
    _remove_phon(sentence)
    return True


def _original_word_forms(sentence):
    return tuple(
        (_tier(word, "FORM", "original").text or "")
        for word in sentence.findall("W")
    )


def _set_sentence_form(sentence, value):
    for kind in ("original", "standard"):
        form = _tier(sentence, "FORM", kind)
        if form is not None:
            form.text = value


def _drop_all_words(sentence):
    for word in list(sentence.findall("W")):
        sentence.remove(word)


def _insert_after(sentence, variant):
    parent = sentence.getparent()
    parent.insert(parent.index(sentence) + 1, variant)


def _materialize_indexed_optional_words(
    relative, sentence, existing_ids, stats
):
    sid = sentence.get("id")
    case = INDEXED_OPTIONAL_WORDS.get((relative, sid))
    if case is None:
        return False
    expected_form, optionals = case
    original = _tier(sentence, "FORM", "original")
    marker = "source indexed optional notation materialized from " + expected_form
    if original is None:
        raise AssertionError(f"{relative}:{sid} has no original FORM")
    if original.text != expected_form:
        if marker in (original.get("notes") or ""):
            return False
        raise AssertionError(
            f"indexed optional FORM drifted for {relative}:{sid}; "
            f"expected {expected_form!r}, found {original.text!r}"
        )

    words = sentence.findall("W")
    for index, expected_word, _ in optionals:
        if index >= len(words):
            raise AssertionError(
                f"indexed optional W{index} missing for {relative}:{sid}"
            )
        actual = _tier(words[index], "FORM", "original")
        actual_text = actual.text if actual is not None else None
        if actual_text != expected_word:
            raise AssertionError(
                f"indexed optional W{index} drifted for {relative}:{sid}; "
                f"expected {expected_word!r}, found {actual_text!r}"
            )

    pristine = copy.deepcopy(sentence)
    variants = []
    groups = len(optionals)
    for mask in range(1 << groups):
        variant = sentence if mask == 0 else copy.deepcopy(pristine)
        choices = tuple(bool(mask & (1 << index)) for index in range(groups))
        rendered = expected_form
        for choice, (_, _, token) in zip(choices, optionals):
            notation = f"({token})"
            if rendered.count(notation) != 1:
                raise AssertionError(
                    f"optional notation {notation!r} drifted for "
                    f"{relative}:{sid}"
                )
            rendered = rendered.replace(notation, token if choice else "", 1)
        _set_sentence_form(variant, _normalize_sentence_form(rendered))

        for choice, (word_index, _, _) in sorted(
            zip(choices, optionals), key=lambda item: item[1][0], reverse=True
        ):
            if not choice:
                variant.remove(variant.findall("W")[word_index])

        new_sid = sid if mask == 0 else f"{sid}-opt{mask}"
        if mask:
            if new_sid in existing_ids:
                raise AssertionError(f"generated sentence id already exists: {new_sid}")
            existing_ids.add(new_sid)
            for audio in variant.xpath(".//AUDIO"):
                audio.getparent().remove(audio)
        _retarget_and_reindex(variant, new_sid)
        variant_original = _tier(variant, "FORM", "original")
        kept = [str(i + 1) for i, value in enumerate(choices) if value]
        omitted = [str(i + 1) for i, value in enumerate(choices) if not value]
        _append_note(
            variant_original,
            marker
            + "; kept group(s): " + (", ".join(kept) if kept else "none")
            + "; omitted group(s): "
            + (", ".join(omitted) if omitted else "none"),
        )
        _remove_phon(variant)
        variants.append(variant)

    parent = sentence.getparent()
    position = parent.index(sentence)
    for offset, variant in enumerate(variants[1:], start=1):
        parent.insert(position + offset, variant)
    stats["indexed optional source sentences expanded"] += 1
    stats["indexed optional readings emitted"] += len(variants)
    return True


def _materialize_rukai_optional_prefix(relative, sentence, existing_ids, stats):
    expected_relative, sid, expected_form = RUKAI_OPTIONAL_PREFIX
    if relative != expected_relative or sentence.get("id") != sid:
        return False
    original = _tier(sentence, "FORM", "original")
    marker = "source optional prefix has no aligned W/M analysis: (taka)"
    if original is None:
        raise AssertionError(f"{relative}:{sid} has no original FORM")
    if original.text != expected_form:
        if marker in (original.get("notes") or ""):
            return False
        raise AssertionError(
            f"Rukai optional-prefix FORM drifted for {sid}; expected "
            f"{expected_form!r}, found {original.text!r}"
        )
    expected_words = (
        "kai=su", "lri-maka-dreele", "kay", "kiucu-ane=li."
    )
    if _original_word_forms(sentence) != expected_words:
        raise AssertionError(
            f"Rukai optional-prefix W analysis drifted for {sid}: "
            f"{_original_word_forms(sentence)!r}"
        )

    full = copy.deepcopy(sentence)
    _set_sentence_form(sentence, expected_form.replace("(taka)", ""))
    _append_note(
        _tier(sentence, "FORM", "original"),
        marker + "; omitted reading retains the source W/M analysis",
    )
    _remove_phon(sentence)
    _retarget_and_reindex(sentence, sid)

    full_sid = f"{sid}-opt1"
    if full_sid in existing_ids:
        raise AssertionError(f"generated sentence id already exists: {full_sid}")
    existing_ids.add(full_sid)
    _set_sentence_form(full, expected_form.replace("(taka)", "taka"))
    _drop_all_words(full)
    for audio in full.xpath(".//AUDIO"):
        audio.getparent().remove(audio)
    _append_note(
        _tier(full, "FORM", "original"),
        marker + "; full reading emitted without W/M tiers to avoid invented alignment",
    )
    _remove_phon(full)
    _retarget_and_reindex(full, full_sid)
    _insert_after(sentence, full)
    stats["Rukai optional unaligned prefix expanded"] += 1
    stats["Rukai optional unaligned-prefix readings emitted"] += 2
    return True


def _materialize_rukai_unaligned_slash(relative, sentence, existing_ids, stats):
    expected_relative, sid, expected_form = RUKAI_UNALIGNED_SLASH_FORM
    if relative != expected_relative or sentence.get("id") != sid:
        return False
    original = _tier(sentence, "FORM", "original")
    marker = (
        "source slash readings samwaesai and samusai have only the "
        "non-corresponding W/M analysis sanguaesay"
    )
    if original is None:
        raise AssertionError(f"{relative}:{sid} has no original FORM")
    if original.text != expected_form:
        if marker in (original.get("notes") or ""):
            return False
        raise AssertionError(
            f"Rukai slash FORM drifted for {sid}; expected {expected_form!r}, "
            f"found {original.text!r}"
        )
    expected_words = (
        "ka", "alisu", "arakay", "ku", "sa-pa-kalrelrem-ane", "la",
        "sanguaesay",
    )
    if _original_word_forms(sentence) != expected_words:
        raise AssertionError(
            f"Rukai slash W analysis drifted for {sid}: "
            f"{_original_word_forms(sentence)!r}"
        )

    alternative = copy.deepcopy(sentence)
    _set_sentence_form(
        sentence,
        "ka alisu arakai ku sapakalrelremane la samwaesai.",
    )
    _drop_all_words(sentence)
    _append_note(
        _tier(sentence, "FORM", "original"),
        marker + "; reading 1 emitted without W/M tiers",
    )
    _remove_phon(sentence)
    _retarget_and_reindex(sentence, sid)

    alt_sid = f"{sid}-alt2"
    if alt_sid in existing_ids:
        raise AssertionError(f"generated sentence id already exists: {alt_sid}")
    existing_ids.add(alt_sid)
    _set_sentence_form(
        alternative,
        "ka alisu arakai ku sapakalrelremane la samusai.",
    )
    _drop_all_words(alternative)
    for audio in alternative.xpath(".//AUDIO"):
        audio.getparent().remove(audio)
    _append_note(
        _tier(alternative, "FORM", "original"),
        marker + "; reading 2 emitted without W/M tiers",
    )
    _remove_phon(alternative)
    _retarget_and_reindex(alternative, alt_sid)
    _insert_after(sentence, alternative)
    stats["Rukai unaligned slash FORM expanded"] += 1
    stats["Rukai unaligned slash readings emitted"] += 2
    return True


def _reorder_words(sentence, order):
    words = sentence.findall("W")
    if sorted(order) != list(range(len(words))):
        raise AssertionError(f"invalid W reorder {order!r}")
    insertion = sentence.index(words[0])
    for word in words:
        sentence.remove(word)
    for offset, index in enumerate(order):
        sentence.insert(insertion + offset, words[index])


def _materialize_rukai_positional_alternative(
    relative, sentence, existing_ids, stats
):
    expected_relative, sid, expected_form = RUKAI_POSITIONAL_ALTERNATIVE
    if relative != expected_relative or sentence.get("id") != sid:
        return False
    original = _tier(sentence, "FORM", "original")
    marker = "source positional alternative materialized from " + expected_form
    if original is None:
        raise AssertionError(f"{relative}:{sid} has no original FORM")
    if original.text != expected_form:
        if marker in (original.get("notes") or ""):
            return False
        raise AssertionError(
            f"Rukai positional alternative FORM drifted for {sid}; expected "
            f"{expected_form!r}, found {original.text!r}"
        )
    expected_words = (
        "w-a-lrumay", "makanaelre", "kay", "la-sinsi", "ki", "la-situ."
    )
    if _original_word_forms(sentence) != expected_words:
        raise AssertionError(
            f"Rukai positional W analysis drifted for {sid}: "
            f"{_original_word_forms(sentence)!r}"
        )

    alternative = copy.deepcopy(sentence)
    _set_sentence_form(
        sentence, "walrumay makanaelre kay lasinsi ki lasitu."
    )
    _append_note(
        _tier(sentence, "FORM", "original"), marker + "; source order 1 retained"
    )
    _remove_phon(sentence)
    _retarget_and_reindex(sentence, sid)

    alt_sid = f"{sid}-alt2"
    if alt_sid in existing_ids:
        raise AssertionError(f"generated sentence id already exists: {alt_sid}")
    existing_ids.add(alt_sid)
    _set_sentence_form(
        alternative, "walrumay kay lasinsi makanaelre ki lasitu."
    )
    _reorder_words(alternative, (0, 2, 3, 1, 4, 5))
    for audio in alternative.xpath(".//AUDIO"):
        audio.getparent().remove(audio)
    _append_note(
        _tier(alternative, "FORM", "original"),
        marker + "; source order 2 emitted with aligned W tiers reordered",
    )
    _remove_phon(alternative)
    _retarget_and_reindex(alternative, alt_sid)
    _insert_after(sentence, alternative)
    stats["Rukai positional alternative expanded"] += 1
    stats["Rukai positional readings emitted"] += 2
    return True


def _apply_explicit_repairs(relative, sentence, existing_ids, stats):
    changed = False
    sid = sentence.get("id")
    indexed_repairs = (
        _materialize_indexed_optional_words,
        _materialize_rukai_optional_prefix,
        _materialize_rukai_unaligned_slash,
        _materialize_rukai_positional_alternative,
    )
    for repair in indexed_repairs:
        if repair(relative, sentence, existing_ids, stats):
            changed = True
    if sid in STRIP_ONLY_SENTENCES:
        changed = _strip_sentence_notation(
            sentence,
            "source slash alternative was already expanded; residual "
            "parenthesis delimiter removed",
        )
        if changed:
            stats["already-expanded slash delimiter repaired"] += 1
    elif sid in CROSS_WORD_KEEP_SENTENCES:
        changed = _strip_sentence_notation(
            sentence,
            "source parenthetical span crosses a partial word boundary; "
            "kept the full source-listed form and emitted no guessed omitted variant",
        )
        if changed:
            stats["ambiguous cross-word span preserved without guessed variant"] += 1

    repairs = (
        ("Saisiyat source column shift repaired", _fix_saisiyat_column_shift),
        ("VOICEOVER label removed", _fix_voiceover_label),
        ("rarely-used annotation moved to notes", _fix_rarely_used_annotation),
        ("Rukai source-surface alternative selected", _fix_rukai_surface_selected_alternative),
        ("Bunun quotative annotation leakage repaired", _fix_bunun_quotative_leak),
    )
    for label, repair in repairs:
        if repair(sentence):
            stats[label] += 1
            changed = True
    return changed


def _scan(text):
    """Return (group_count, balanced) for non-nested ASCII parentheses."""
    count = 0
    depth = 0
    for char in text or "":
        if char == "(":
            if depth:
                return count, False
            depth = 1
            count += 1
        elif char == ")":
            if not depth:
                return count, False
            depth = 0
    return count, depth == 0


def _transform_texts(texts, choices, expected_groups):
    output = []
    group = -1
    active = None
    for text in texts:
        chars = []
        for char in text or "":
            if char == "(":
                if active is not None:
                    raise AssertionError(f"nested parenthesis in {text!r}")
                group += 1
                active = group
                continue
            if char == ")":
                if active is None:
                    raise AssertionError(f"unmatched closing parenthesis in {text!r}")
                active = None
                continue
            if active is None or choices[active]:
                chars.append(char)
        output.append("".join(chars))
    if active is not None:
        raise AssertionError("unmatched opening parenthesis across element sequence")
    if group + 1 != expected_groups:
        raise AssertionError(
            f"expected {expected_groups} groups, saw {group + 1} in {texts!r}"
        )
    return output


def _normalize_sentence_form(text):
    text = re.sub(r"\s+", " ", text or "").strip()
    text = re.sub(r"\s+([.,!?;:，。！？；：])", r"\1", text)
    return text


def _contentless(text):
    return not text or bool(_PUNCT_ONLY.fullmatch(text))


def _transform_tier(elements, choices, groups, *, sentence_level=False):
    values = _transform_texts(
        [element.text or "" for element in elements], choices, groups
    )
    for element, value in zip(elements, values):
        element.text = _normalize_sentence_form(value) if sentence_level else value


def _transform_variant(sentence, choices, groups, source_form):
    for kind in ("original", "standard"):
        element = _tier(sentence, "FORM", kind)
        if element is not None:
            _transform_tier([element], choices, groups, sentence_level=True)

        words = [w for w in sentence.findall("W")
                 if _tier(w, "FORM", kind) is not None]
        _transform_tier(
            [_tier(word, "FORM", kind) for word in words],
            choices,
            groups,
        )

        morphs = [m for m in sentence.xpath("./W/M")
                  if _tier(m, "FORM", kind) is not None]
        if morphs:
            _transform_tier(
                [_tier(morph, "FORM", kind) for morph in morphs],
                choices,
                groups,
            )

    # Drop empty optional morphemes first, then empty optional words.
    for morph in list(sentence.xpath("./W/M")):
        original = _tier(morph, "FORM", "original")
        if original is not None and _contentless(original.text or ""):
            morph.getparent().remove(morph)
    for word in list(sentence.findall("W")):
        original = _tier(word, "FORM", "original")
        if original is not None and _contentless(original.text or ""):
            sentence.remove(word)

    # Parentheses in source glosses mirror the selected optional phrase in
    # the remaining subtree.  Removed W/M nodes already took their glosses
    # with them; on surviving nodes only the analytic delimiters are removed.
    for translation in sentence.xpath("./W/TRANSL | ./W/M/TRANSL"):
        if translation.text:
            translation.text = _strip_parens(translation.text)

    original = _tier(sentence, "FORM", "original")
    kept = [str(index + 1) for index, choice in enumerate(choices) if choice]
    omitted = [str(index + 1) for index, choice in enumerate(choices) if not choice]
    _append_note(
        original,
        "source optional notation materialized from " + source_form
        + "; kept group(s): " + (", ".join(kept) if kept else "none")
        + "; omitted group(s): " + (", ".join(omitted) if omitted else "none"),
    )
    _remove_phon(sentence)


def _retarget_and_reindex(sentence, new_sid):
    sentence.set("id", new_sid)
    for word_index, word in enumerate(sentence.findall("W")):
        word_id = f"{new_sid}_W{word_index}"
        word.set("id", word_id)
        for morph_index, morph in enumerate(word.findall("M"), start=1):
            morph.set("id", f"{word_id}M{morph_index}")


def _set_rukai_optional_translation(sentence, keep):
    if not sentence.get("id", "").startswith("20200429-CL-6_S_19"):
        return
    if keep:
        _set_primary_translation(
            sentence, "eng", "I hate to eat pork; do you like to eat pork?"
        )
        _set_primary_translation(
            sentence, "zho", "我不喜歡吃豬肉，你喜歡吃豬肉嗎？"
        )
    else:
        _set_primary_translation(
            sentence, "eng", "I hate to eat pork; do you like it?"
        )
        _set_primary_translation(sentence, "zho", "我不喜歡吃豬肉，你喜歡嗎？")


def _materialize_sentence(sentence, existing_ids, stats):
    original = _tier(sentence, "FORM", "original")
    source_form = original.text or "" if original is not None else ""
    word_text = " ".join(
        (_tier(word, "FORM", "original").text or "")
        for word in sentence.findall("W")
        if _tier(word, "FORM", "original") is not None
    )
    morph_text = " ".join(
        (_tier(morph, "FORM", "original").text or "")
        for morph in sentence.xpath("./W/M")
        if _tier(morph, "FORM", "original") is not None
    )
    word_groups, word_balanced = _scan(word_text)
    if word_groups == 0 and word_balanced:
        return False

    groups, balanced = _scan(source_form)
    if not balanced:
        raise AssertionError(
            f"unbalanced parenthesis remains in {sentence.get('id')}: {source_form!r}"
        )
    if groups == 0:
        return False

    for label, text in (("W", word_text), ("M", morph_text)):
        count, ok = _scan(text)
        if not ok or count != groups:
            raise AssertionError(
                f"{sentence.get('id')}: S has {groups} balanced group(s), "
                f"{label} has {count} and balanced={ok}: {text!r}"
            )

    sid = sentence.get("id")
    parent = sentence.getparent()
    pristine = copy.deepcopy(sentence)
    variants = []
    for mask in range(1 << groups):
        variant = sentence if mask == 0 else copy.deepcopy(pristine)
        choices = tuple(bool(mask & (1 << index)) for index in range(groups))
        if mask:
            for audio in variant.xpath(".//AUDIO"):
                audio.getparent().remove(audio)
            new_sid = f"{sid}-opt{mask}"
            if new_sid in existing_ids:
                raise AssertionError(f"generated sentence id already exists: {new_sid}")
            existing_ids.add(new_sid)
        else:
            new_sid = sid
        _transform_variant(variant, choices, groups, source_form)
        _retarget_and_reindex(variant, new_sid)
        _set_rukai_optional_translation(variant, choices[0])
        variants.append(variant)

    position = parent.index(sentence)
    for offset, variant in enumerate(variants[1:], start=1):
        parent.insert(position + offset, variant)
    stats["optional source sentences expanded"] += 1
    stats["optional readings emitted"] += len(variants)
    stats[f"sentences with {groups} optional group(s)"] += 1
    return True


def _strip_analysis_only_parentheses(sentence, stats):
    original = _tier(sentence, "FORM", "original")
    if original is not None and ("(" in (original.text or "") or ")" in (original.text or "")):
        return False
    forms = sentence.xpath("./W/FORM | ./W/M/FORM")
    if not any(element.text and ("(" in element.text or ")" in element.text)
               for element in forms):
        return False
    for element in forms:
        if element.text:
            element.text = _strip_parens(element.text)
    _append_note(
        original,
        "source W/M analysis parentheses removed because the sentence FORM "
        "already supplies the attested surface",
    )
    _remove_phon(sentence)
    stats["analysis-only parentheses stripped to attested S surface"] += 1
    return True


def serialize(tree):
    return etree.tostring(tree, xml_declaration=True, encoding="UTF-8")


def process_file(path, dry_run, stats, relative=None):
    relative = relative or Path(path).name
    original_bytes = Path(path).read_bytes()
    tree = etree.parse(path)
    if serialize(tree) != original_bytes:
        stats["file skipped: round-trip guard"] += 1
        return False
    root = tree.getroot()
    existing_ids = {s.get("id") for s in root.iter("S")}
    modified = False

    for sentence in list(root.iter("S")):
        if _apply_explicit_repairs(relative, sentence, existing_ids, stats):
            modified = True

    for sentence in list(root.iter("S")):
        if _materialize_sentence(sentence, existing_ids, stats):
            modified = True

    for sentence in list(root.iter("S")):
        if _strip_analysis_only_parentheses(sentence, stats):
            modified = True

    for sentence in root.iter("S"):
        for element in sentence.xpath("./W/FORM | ./W/M/FORM"):
            if element.text and ("(" in element.text or ")" in element.text):
                raise AssertionError(
                    f"residual W/M parenthesis in {sentence.get('id')}: "
                    f"{element.text!r}"
                )

    if modified and not dry_run:
        Path(path).write_bytes(serialize(tree))
    return modified


def main():
    corpus = Path(__file__).resolve().parents[2]
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--xml_dir", default=str(corpus / "XML"))
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    stats = collections.Counter()
    files = 0
    for directory, _, filenames in os.walk(args.xml_dir):
        for filename in sorted(filenames):
            if not filename.endswith(".xml"):
                continue
            path = os.path.join(directory, filename)
            relative = str(Path(path).relative_to(args.xml_dir))
            if process_file(path, args.dry_run, stats, relative):
                files += 1
                print(f"  modified: {Path(path).relative_to(args.xml_dir)}")
    print(f"\nfiles {'that would be ' if args.dry_run else ''}modified: {files}")
    for label, count in stats.most_common():
        print(f"  {count:5d}  {label}")


if __name__ == "__main__":
    main()
