name: Token Count Delta
on:
  workflow_dispatch:
    inputs:
      parameter:
        description: My Parameter
  pull_request:  # This was the line with incorrect indentation
    
jobs:
  compare-token-counts:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout latest commit
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Needed for full git history
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Set up packages
      run: |
        python3 -m pip install -r requirements.txt
    - name: Create temp analysis directory
      run: mkdir -p /tmp/token_analysis
    - name: Copy token scripts to temp folder
      run: |
        cp QC/count_tokens.py /tmp/token_analysis/
        cp QC/tokens_delta.py /tmp/token_analysis/
        cp QC/plot_deltas.py /tmp/token_analysis/
    - name: Run token count on latest commit
      run: |
        python3 /tmp/token_analysis/count_tokens.py ./Corpora > /tmp/current_token_count.json
    - name: Get commit from 6 months ago
      id: oldcommit
      run: |
        OLD_COMMIT=$(git rev-list -1 --before="6 months ago" origin/main)
        echo "commit_sha=$OLD_COMMIT" >> $GITHUB_OUTPUT
    - name: Checkout repo at old commit
      run: git checkout ${{ steps.oldcommit.outputs.commit_sha }}
    - name: Run token count on old commit
      run: |
        python3 /tmp/token_analysis/count_tokens.py ./Corpora > /tmp/old_token_count.json
    - name: Compute token deltas
      run: |
        python3 /tmp/token_analysis/tokens_delta.py \
          /tmp/old_token_count.json \
          /tmp/current_token_count.json \
          /tmp/token_delta.json
    - name: Show token delta
      run: cat /tmp/token_delta.json
    - name: Generate plots
      run: python3 /tmp/token_analysis/plot_deltas.py /tmp/token_delta.json
    - name: Upload plot artifact
      uses: actions/upload-artifact@v4
      with:
        name: language-dialect-deltas
        path: language_dialect_deltas.png